name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment: oquanta-prod
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> .env.local

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Node packages
        run: yarn

      - name: Install Node packages
        run: yarn pull-contentful-data 

      - name: Build assets
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oquanta-com
          include-hidden-files: true
          path: |
            dist
  deploy:
    environment: oquanta-prod
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_ARGS: -o StrictHostKeyChecking=no -v
      DEPLOY_FOLDER: ${{ secrets.IONOS_HOSTING_ROOT }}/deploy/oquanta-com
      DEPLOY_PATH: ${{ secrets.IONOS_HOSTING_ROOT }}/deploy/oquanta-com/${{ github.run_id }}/
      APP_PATH: ${{ secrets.IONOS_HOSTING_ROOT }}/oquanta-com
      DEPLOYMENTS_TO_KEEP: 3
    steps:
      - uses: actions/checkout@v4
      # Make sure the @v0.9.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: oquanta-com
          path: ${{ github.workspace }}/artifact

      - name: Prepare deployment folder
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "mkdir -p $DEPLOY_PATH && chmod 0774 $DEPLOY_PATH"

      - name: rsync deployments
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET: $DEPLOY_PATH
          VERBOSE: true
          USER: ${{ secrets.DEPLOY_USER }}
          ARGS: -avq --progress
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: artifact

      - name: Set permissions to folders
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "find ./deploy/oquanta-com/${{ github.run_id }} -type d -exec chmod 0755 {} + && find ./deploy/oquanta-com/${{ github.run_id }} -type f -exec chmod 0644 {} +"

      - name: Set permissions to files
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "find ./deploy/oquanta-com/${{ github.run_id }} -type f -exec chmod 0644 {} +"

      - name: Create symlink to real path
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "ln -sfn ./deploy/oquanta-com/${{ github.run_id }} ./oquanta-com"

      # list all folders in ./deploy/oquanta-com/ remove all but last $DEPLOYMENTS_TO_KEEP created
      - name: Remove old deployments
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "cd ./deploy/oquanta-com && ls -t | tail -n +$((DEPLOYMENTS_TO_KEEP+1)) | xargs rm -rf"

      # zip each folder in ./deploy/oquanta-com but ${{ github.run_id }}
      - name: Archive old deployments
        run: |
          ssh $SSH_ARGS ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "cd ./deploy/oquanta-com && ls -t | tail -n +$((DEPLOYMENTS_TO_KEEP+1)) | xargs -I {} tar -czf {}.tar.gz {}"
